### ISSUE TITLE
Website access

### ISSUE THREAD

**Issue by kazlauskis** [NERC-CEH/st-helena-app#1]
@BirenRathod @DavidRoy please can I get admin access to the new St Helena website? Also, its linked warehouse if it uses something other than warehouse1.

Thanks!

**Comment by BirenRathod** [comment]
@kazlauskis did you register on live site? here is the website address -> https://irecordsthelena.edu.sh/

**Comment by kazlauskis** [comment]
Thanks, I've registered my account now.

**Comment by BirenRathod** [comment]
@kazlauskis you are now admin and site is syched to live warehouse.

**Comment by kazlauskis** [comment]
Great, is it hosted on the Pantheon? Can you give me access there as well?

**Comment by BirenRathod** [comment]
@kazlauskis that's done.

**Comment by kazlauskis** [comment]
Thanks!
