### ISSUE TITLE
Failure to upload records

### ISSUE THREAD

**Issue by selenegough** [NERC-CEH/st-helena-app#3]
Issue description:
I have 25 pending surveys ranging from  2022-2023, all with images and additional info. I wanted to use the ‘Upload All’ button, so I waited till I had a good (enough) internet connection to upload them. After pressing the Upload All button, all of the records had a pending icon (where the upload button would usually be displayed on each tab). However after a minute or two I was met with the notification that said “Sorry Load failed”. I figured it must have timed out with a low bandwidth trying to upload so much data at once, so I tried uploading the records individually but I was met with the same message “Sorry Load failed”. And, now can’t upload any records from my device.

1.	Click Upload All button
2.	Records seem to be trying to upload
3.	After waiting for a minute – displayed with the “Sorry Load failed” text box
4.	Retried by uploading records one by one and met again with the message “Sorry Load failed”
5.	Now, unable to upload records at all.

Expected behaviour:
1.	Click Upload All button
2.	Records seem to be trying to upload
3.	After waiting for a minute – all records are uploaded and can be found under the Uploaded tab

Screenshots:
![image](https://user-images.githubusercontent.com/94616675/220333638-13642808-4255-422d-a29b-4e0e4d2f8b02.png)

Device information:
iPhone 13, iOS 16.1.1
App version: v6.0.3 (18)

**Comment by Vilius-Stankaitis** [comment]
Hi, 

I need a bit more information. 

Could you try re-login and then upload (individually and all)?
Do you get the same error message if you are uploading a single record? 
Could you create a dummy test record and see if it uploads? 

Sorry for the inconvenience,
Vilius

**Comment by selenegough** [comment]
Hi,

After closing the app fully and then re-opening, I tried to upload each record individually (so pressing upload and waiting for the record to be moved from the 'Pending' tab to the 'Uploads' tab) and that works, note this does take around 4+ minutes to upload one single record. 
However when trying to use the 'Upload all' feature or pressing upload on a few records at once (I'm sure I pressed upload on at least 4 individual records at once) I'm left with the message:
![IMG_0954](https://user-images.githubusercontent.com/94616675/221574242-b66a0d0d-83f5-4c0e-bb53-992c89295f4d.PNG)
Just to highlight again, uploading one record (from the pending tab to uploads tab) at a time does work for me now, just not uploading multiple records at once or using the Upload all feature. Would you still like me to try the things you suggested anyways?

Hope that makes sense? 
Thanks,
Selene

**Comment by Vilius-Stankaitis** [comment]
It's unclear why it's taking so long to upload the record.  

Do you have a good internet connection when uploading records? 
Are other testers experiencing similar uploading issues? 

Upload time also depends on how many images the record has. Uploading records without images should be really fast.

**Comment by Vilius-Stankaitis** [comment]
Could you try now? It should upload faster

**Comment by selenegough** [comment]
The internet connection is the best I can possibly get. Nobody else has come back to say that they're having issues with uploading records.

I'm currently in the field with poor cell reception for data and, my home broadband has little to no megabytes left. So I will try uploading records tomorrow (1st of a new month = more megabytes...problems of living on St Helena!)

**Comment by kazlauskis** [comment]
@selenegough thanks for the report. Unfortunately, this is tricky, and I don't have a solution yet. There might be high latency (i.e. delay) for network communications from St Helena. All the app's data has to travel to the UK and back to you, which is a relatively long distance from your location. If uploading a single record takes more than a minute, the network connection could be better, or the website could be faster. It is hard to say what the case is because when we're testing, it typically processes a new record with a few images within 10 seconds here in Europe.

**Comment by selenegough** [comment]
Okay @kazlauskis thank you. We shall note it could be related to St Helena's bandwidth and, at least now we know what could possibly be the problem and let users know that we are aware of this issue. We're expecting fibre optic to be operational (hopefully within the next year), possibly a solution?

**Comment by kazlauskis** [comment]
Yes, users should have a decent network connection for the app to sync the records with photos to the UK. I am closing this ticket for now.
